DATABASE_USER: root
DATABASE_PASSWORD: julian
DATABASE_HOST: localhost
DATABASE_PORT: 3306
DATABASE_ENGINE: django.db.backends.mysql
DATABASE_NAME: Dssd_employees_app
TESTSUITE_DATABASE_NAME: Dssd_employees_app_test

SECRET_KEY: 'dd3n0v_!nbc4@+=b!gt&@1rg)podb2r!iuyknnj0$0rgle9uiy'